services:
  postgres_db_dev:
    image: postgres:13
    container_name: postgres_db_dev
    environment:
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=app
    ports:
      - "25432:5432"
    volumes:
      - ./postgres-config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - dev_postgres_data:/var/lib/postgresql/data
    networks:
      - pg_database_network
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

volumes:
  dev_postgres_data:


networks:
  pg_database_network:
    driver: bridge
